[unix_http_server]
file=/tmp/supervisor_social_media.sock
chmod=0700

[inet_http_server]
port=0.0.0.0:9010

[supervisord]
logfile=./logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisor_social_media.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor_social_media.sock

[program:service_social_media]
command=gunicorn -c ./config/gunicorn.py --timeout 120 app.app:app --preload
autostart=true
autorestart=true
startsecs=1
stopwaitsecs=1
stopsignal=TERM
killasgroup=true
stdout_logfile=logs/gunicorn_stdout.log
stderr_logfile=logs/gunicorn_stderr.log

[include]
files=supervisord.conf
